name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - notebook=7.0.3
  - nodejs
  - pip:
      - mlflow==2.16.2
      - wandb==0.18.0
      - pydantic
      - ydata-profiling
      - ipywidgets
