name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - mlflow==2.16.2
      - wandb==0.18.0
      - hydra-core
      - omegaconf
