name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - pandas=2.1.3
  - numpy=1.26.4
  - pip:
      - mlflow==2.16.2
      - wandb==0.18.0
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
